# TODO: create docker-compose file

version: '3.9'
services:
  auth-api:
    build:
      dockerfile: Dockerfile
      context: ../tempest-administration-service
    ports:
      - "8083:8083"
    environment:
      - ADMINISTRATION_DB_HOST=auth-db
      - ADMINISTRATION_DB_SERVICE_PASS=123LocalDBPass
      - ADMINISTRATION_DB_PORT=5432
      - HMAC_SIGNING_KEY=123PassID
    networks:
      - gateway-network
      - administration-network
    depends_on:
      - auth-db
  auth-db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_DB=administration_db
      - POSTGRES_USER=service
      - POSTGRES_PASSWORD=123LocalDBPass
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      # copy the sql script to create tables
      - ./db/migrations/0_init.up.sql:/docker-entrypoint-initdb.d/0_init.up.sql
    networks:
      - administration-network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "service",
          "-d",
          "administration_db",
          "-h",
          "localhost"
        ]
      interval: 5s
      retries: 5
      timeout: 5s

  gateway-api:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DATA_SERVICE_HOST=http://localhost:8081
      - AUTH_SERVICE_HOST=http://auth-api
      - AUTH_SERVICE_PORT=8083
    ports:
      - "8082:8082"
    networks:
      - gateway-network
    depends_on:
      - auth-api

networks:
  gateway-network:
    driver: bridge
  administration-network:
    driver: bridge
