gateway-service-config:
  host: "0.0.0.0"
  port: 8080
endpoints:
- user-service:
    host: ${USER_SERVICE_HOST}
    port: ${USER_SERVICE_PORT}
auth:
  host: ${AUTH_SERVICE_HOST}
  port: ${AUTH_SERVICE_PORT}
